### PR TITLE
create docker integration

### PR DESCRIPTION
**Pull request by jctt1983**
- python 2.7
- mysql 8.019
- rabbit mq
- nginx
- celery

### CODE REVIEW

**Comment by gabriel-tessier** [comment]
Pushed small changes in Readme and config file....
I was not able to set correctly the path, actually it's not clear for me which path to set.
APP_BASE_PATH <--- this one I set the directory of the downloaded source, the one which contain .evn file etc...
APP_DATA_PATH <--- Here it's written will contain Media etc... so I put /home/gab/HeadUp/static???

CELERY_BASE_PATH <--- I put same as APP_BASE_PATH

CELERY_DATA_PATH <--- I put /home/gab/HeadUp/logs??

I can't figure out which folder to set as my docker was returning error and they expect to find some lib folders that I don't have anywhere???!!!

> Cannot create container for service headup_rabbitmq: invalid mount config for type "bind": bind source path does not exist: /home/gab/HeadUp/static/lib/rabbitmq

Same error for mysql container.

Can you give some direction on which path to set?

**Comment by jctt1983** [comment]
APP_BASE_PATH  is same APP_DATA_PATH

APP_DATA_PATH should be somewhere where the logs, images, mysql data folder will be located. So it should not be same as flask static folder.


APP_BASE_PATH  = /home/gab/HeadUp/app
APP_DATA_PATH = /home/gab/HeadUp/appData

CELERY_BASE_PATH = /home/gab/HeadUp/app
CELERY_DATA_PATH = /home/gab/HeadUpCelery/celeryData

Then each container should create the folders it needs to start. I only tried this in Windows 10 with admin privilege. Maybe there's a different story with linux, you might need to set some permissions to allow the container to create those folders for you.

**Comment by gabriel-tessier** [comment]
Got it I'll try and will update the doc for linux.

**Comment by gabriel-tessier** [comment]
Still have the same error... 

You use volume bind in docker compose, it works for app as the source folder exist but it not work for mysql and rabbitmq as the folders doesn't exist....
May need to run something to create the lib folders???
If you try to reinstall from scratch does it work, look like you create the lib folder before.
I also check the dockerfile and the images I found nowhere where it write the lib folders.

**Comment by jctt1983** [comment]
I tried in Windows 10 by removing the data folder then 

```bash
$ docker-compose build

$ docker-compose up -d
```

With the second one, all folders will be created. The respective containers will create the folders if they don't exists. 

I think in Windows, I don't worry about permissions in the folders because I run everything as Administrator. So in Linux the story might be different. I should try with Linux and see what's happening

**Pull request merged**
